name: EcmaScript official test suite (test262)
on:
  schedule:
    # Run every day at midnight.
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run_test262:
    name: Run the test262 test suite
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout the main Boa repository
        uses: actions/checkout@v4
        with:
          repository: jasonwilliams/boa
          ref: remove-ghpages
          submodules: true
          path: boa
      - name: Install the Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            target
            ~/.cargo/git
            ~/.cargo/registry
          key: ${{ runner.os }}-cargo-test262-${{ hashFiles('**/Cargo.lock') }}

      # Run the test suite.
      - name: Run the test262 test suite
        run: |
          cd boa
          mkdir ../results
          cargo run --release --bin boa_tester -- run -v -o ../results/test262
          cd ..
      - name: Checkout the website-data repository
        uses: actions/checkout@v4
        with:
          path: website-data
      - name: Commit files
        run: |
          cp -r ./results/test262/* ./website-data/test262/
          cd website-data
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add test262
          git commit -m "Add new test262 results" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
